name: CI

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'client/**'
      - 'server/**'

jobs:

  build-and-test-pull-request:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build server
        run: |
          npm install --prefix server &&
          npm run build --prefix server &&
          npm run lint --prefix server
      - name: Install and build client
        run: |
          npm install --prefix client &&
          npm run build --prefix client &&
          npm run lint --prefix client